### ISSUE TITLE
wstart error

### ISSUE THREAD

**Issue by d009** [estnltk/episode-miner#17]
Kui leksikonis on kattuvad üksused (nagu "kuu" ja "kuupäev"), siis läheb time_scale='wstart' valides asi katki:

``` python
event_texts = []
event_vocabulary2 = [
                     {'term': 'kuupäev'},
                    {'term': 'kuu'}]  

event_tagger = EventTagger(event_vocabulary2, search_method='ahocorasick', case_sensitive=True,
                           conflict_resolving_strategy='ALL', return_layer=True)

text = '''13. kuupäev ei kõla hästi.'''
event_text = EventText(text, event_tagger = event_tagger)
event_texts.append(event_text)
event_sequences = EventSequences(event_texts=event_texts, classificator='term', time_scale='wstart')
```

annab KeyErrori

**Comment by urdvr** [comment]
@paultammo oskad sa kommenteerida/lahendada?

**Comment by paultammo** [comment]
Kui `conflict_resolving_strategy='ALL'`, siis `event_text`i sisse võivad tekkida kattuvad sündmused. Kattuvate sündmuste korral ei saa (mõistlikult) arvutada atribuute `wstart` ja `cstart` ning seepärast ta katki läks.
Kasuta `conflict_resolving_strategy='ALL'` asemel `conflict_resolving_strategy='MAX'` või `conflict_resolving_strategy='MIN'` või `time_scale='wstart'` asemel näiteks `time_scale='wstart_raw'`.

**Comment by urdvr** [comment]
Ma teen selle issue uuesti lahti, et @d009 saaks kommenteerida, kas teie arusaamad ühtivad.

**Comment by d009** [comment]
Jah, pakutud variandid töötavad, aga mida wstart_raw endast kujutab, dokist leida ei õnnestunud.
